spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.43.104:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qianluohan

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.qianluohan: info
  file:
    name: log/blog.log
server:
  port: 8081