spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.114.219:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    cn.com.zyb: info
  file:
    name: log/blog.log
server:
  port: 8081